name: mypipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: Self-hosted
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: second step or task
        run: echo Second Step!!!!
      - name: create file and list it
        run: |
          touch newFile.txt
          ls -l
          sleep 10
